spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: book
    password: book
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
server:
  servlet:
    encoding:
      force: true